{% set name = "premailer" %}
{% set version = "3.4.1" %}
{% set sha256 = "e8ad94c32dc1b3f1fe21f6bf9912ec10149e99106d097463ac6955fb49f84668" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml
    - cssselect
    - cssutils
    - requests
    - argparse  # [py26]
    - orderedict  # [py26]

test:
  imports:
    - premailer

about:
  home: http://github.com/peterbe/premailer
  license: BSD3
  summary: Turns CSS blocks into style attributes

extra:
  recipe-maintainers:
    - vamega
