appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: C02lShczVOcaxvZ7ze13ThbiBqNdqQ4+/6qCKQ31sRb8f7dwGUTRYZiG4aih8u4Qu2IkqtvR8VYfDKX/jjhYBz94qY/ALYbMwRdeif3rHQ5+/tUUpaoFC3pCFvySFMrfgMjsduuc8PiPcgVNILLeRUVl+nDEx0TOTU2/vHMEw7vNgmRVBqSMZdDo5kRqOSeSpuR3ceH2hdK1jZfjov1+rBXrpG57jPQCNs7xKDZip/jy9TXuibTkI2JV6vxUQRZPfmSiXVhMtNEZtAtea5tLbaHc1U0gaj+C6j5sVfI0SMxo6r/5ilAnK9zyt/vTUHeHsDx4+6zcCov5a6HANN+M1DlHZxroZgJYm2LfZrbfAixWTdRbgU+R+d5S5RmeILeqDji+Cp+ZkNGze+rGngKWd98ymIAjDJ+107+ve40E23uQH+uyKy1KQvs+DvrM4IWBcy2ZW3XomNBewVHPiiYUwC9A0uSepVrFwAQUDsUG7PaFtQ/VIRgX5Rm0/2OaPc48RvBx78oiUKjdZfHMaFFZ+EIOPr/Z5fQT8ORO7ccokXz8uc2LvpQ6dWFZq/kauBvS2Ma5JbIVTU+0Qh4qbvXRe91bcSeN+V02PJTJDtUd/8Epdhp2npNnTkRmoBSdz+P3+GoRN2tLLzKD0SY1n6gJlqwzhLGSoAp8Vjmka0gZBk0=}
